<a href="https://colab.research.google.com/github/JosueAfouda/IBM-Applied-Data-Science-with-R/blob/main/afouda_final_jupyter_covid19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>
<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/M5_Final/images/SN_web_lightmode.png" width="300">
</center>

<h1>Analysis of Global COVID-19 Pandemic Data</h1>

Estimated time needed: **90** minutes

## Overview:

There are 10 tasks in this final project. All tasks will be graded by your peers who are also completing this assignment within the same session.

You need to submit the following the screenshot for the code and output for each task for review.

If you need to refresh your memories about specific coding details, you may refer to previous hands-on labs for code examples.

In [1]:
# If you are working on your local Jupyter notebook, please uncomment the below code and install the packages

install.packages("httr")
install.packages("rvest")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [2]:
#require("httr")
#require("rvest")

library(httr)
library(rvest)

Note: if you can import above libraries, please use install.packages() to install them first.

## TASK 1: Get a `COVID-19 pandemic` Wiki page using HTTP request

First, let's write a function to use HTTP request to get a public COVID-19 Wiki page.

Before you write the function, you can open this public page from this

URL https://en.wikipedia.org/w/index.php?title=Template:COVID-19_testing_by_country using a web browser.

The goal of task 1 is to get the html page using HTTP request (`httr` library)

In [3]:

get_wiki_covid19_page <- function() {

  # Our target COVID-19 wiki page URL is: https://en.wikipedia.org/w/index.php?title=Template:COVID-19_testing_by_country
  # Which has two parts:
    # 1) base URL `https://en.wikipedia.org/w/index.php
    # 2) URL parameter: `title=Template:COVID-19_testing_by_country`, seperated by question mark ?

  # Wiki page base
  wiki_base_url <- "https://en.wikipedia.org/w/index.php"
  # You will need to create a List which has an element called `title` to specify which page you want to get from Wiki
  # in our case, it will be `Template:COVID-19_testing_by_country`

  # - Use the `GET` function in httr library with a `url` argument and a `query` arugment to get a HTTP response
  response <- GET(
    url = wiki_base_url,
    query = list(title = "Template:COVID-19 testing by country")
  )

  # Use the `return` function to return the response
  return(response)

}

Call the `get_wiki_covid19_page` function to get a http response with the target html page

In [4]:
# Call the get_wiki_covid19_page function and print the response
html_content <- get_wiki_covid19_page()
print(html_content)

Response [https://en.wikipedia.org/wiki/Template:COVID-19_testing_by_country]
  Date: 2023-08-29 12:56
  Status: 200
  Content-Type: text/html; charset=UTF-8
  Size: 446 kB
<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-fea...
<head>
<meta charset="UTF-8">
<title>Template:COVID-19 testing by country - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-heade...
"wgRequestId":"d3c16144-790e-460e-887b-a58b5f3db226","wgCanonicalNamespace":"...
"CS1 uses Khmer-language script (km)","CS1 Khmer-language sources (km)","CS1 ...
"CS1 Mongolian-language sources (mn)","CS1 foreign language sources (ISO 639-...
"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVarian...
...

## TASK 2: Extract COVID-19 testing data table from the wiki HTML page

On the COVID-19 testing wiki page, you should see a data table `<table>` node contains COVID-19 testing data by country on the page:

<a href="https://cognitiveclass.ai/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkRP0101ENCoursera889-2023-01-01">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/M5_Final/images/covid-19-by-country.png" width="400" align="center">
</a>

Note the numbers you actually see on your page may be different from above because it is still an on-going pandemic when creating this notebook.

The goal of task 2 is to extract above data table and convert it into a data frame

Now use the `read_html` function in rvest library to get the root html node from response

In [5]:
# Get the root html node from the http response in task 1
root_html_node <- read_html(html_content)

Get the tables in the HTML root node using `html_nodes` function.

In [6]:
# Get the table node from the root html node
table_node <- html_table(root_html_node)
print(table_node)

[[1]]
# A tibble: 1 × 2
  X1    X2
  <lgl> <chr>
1 NA    This template needs to be updated.  Please help update this template to…

[[2]]
# A tibble: 173 × 9
   `Country or region` `Date[a]`   Tested      `Units[b]` `Confirmed(cases)`
   <chr>               <chr>       <chr>       <chr>      <chr>
 1 Afghanistan         17 Dec 2020 154,767     samples    49,621
 2 Albania             18 Feb 2021 428,654     samples    96,838
 3 Algeria             2 Nov 2020  230,553     samples    58,574
 4 Andorra             23 Feb 2022 300,307     samples    37,958
 5 Angola              2 Feb 2021  399,228     samples    20,981
 6 Antigua and Barbuda 6 Mar 2021  15,268      samples    832
 7 Argentina           16 Apr 2022 35,716,069  samples    9,060,495
 8 Armenia             29 May 2022 3,099,602   samples    422,963
 9 Australia           9 Sep 2022  78,548,492  samples    10,112,229
10 Austria             1 Feb 2023  205,817,752 samples    5,789,991
# ℹ 163 more rows
# ℹ 4 more variables: `Confirmed /tested,%` <chr>,
#   `Tested /population,%` <chr>, `Confirmed /population,%` <chr>, Ref. <chr>

[[3]]
# A tibble: 1 × 2
  X1    X2
  <lgl> <chr>
1 NA    "This template uses TemplateStyles:\nTemplate:COVID-19 testing by count…

[[4]]
# A tibble: 1 × 5
  Parameter Parameter Description    Type    Status
  <chr>     <chr>     <chr>          <chr>   <chr>
1 state     state     no description Unknown optional

Read the specific table from the multiple tables in the `table_node` using the `html_table` function and convert it into dataframe using `as.data.frame`

_Hint:- Please read the `table_node` with index 2(ex:- table_node[2])._

In [7]:
# Read the table node and convert it into a data frame, and print the data frame for review
covide19_data <- table_node[[2]]
head(covide19_data)
tail(covide19_data)

  Country or region   Date[a]     Tested  Units[b] Confirmed(cases)
1 Afghanistan         17 Dec 2020 154,767 samples  49,621
2 Albania             18 Feb 2021 428,654 samples  96,838
3 Algeria             2 Nov 2020  230,553 samples  58,574
4 Andorra             23 Feb 2022 300,307 samples  37,958
5 Angola              2 Feb 2021  399,228 samples  20,981
6 Antigua and Barbuda 6 Mar 2021  15,268  samples  832
  Confirmed /tested,% Tested /population,% Confirmed /population,% Ref.
1 32.1                0.40                 0.13                    [1]
2 22.6                15.0                 3.4                     [2]
3 25.4                0.53                 0.13                    [3][4]
4 12.6                387                  49.0                    [5]
5 5.3                 1.3                  0.067                   [6]
6 5.4                 15.9                 0.86                    [7]

  Country or region
1 Uzbekistan
2 Venezuela
3 Vietnam
4 Zambia
5 Zimbabwe
6 .mw-parser-output .reflist{font-size:90%;margin-bottom:0.5em;list-style-type:decimal}.mw-parser-output .reflist .references{font-size:100%;margin-bottom:0;list-style-type:inherit}.mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}.mw-parser-output .reflist-columns{margin-top:0.3em}.mw-parser-output .reflist-columns ol{margin-top:0}.mw-parser-output .reflist-columns li{page-break-inside:avoid;break-inside:avoid-column}.mw-parser-output .reflist-upper-alpha{list-style-type:upper-alpha}.mw-parser-output .reflist-upper-roman{list-style-type:upper-roman}.mw-parser-output .reflist-lower-alpha{list-style-type:lower-alpha}.mw-parser-output .reflist-lower-greek{list-style-type:lower-greek}.mw-parser-output .reflist-lower-roman{list-style-type:lower-roman}\n^ Local time.\n\n^ For some countries it is unclear whether they report samples or cases. One person tested twice is recorded as one case and two samples.\n\n^ Excluding Taiwan.\n\n^ Excluding Northern Cyprus.\n\n^ Excluding Greenland and the Faroe Islands.\n\n^ Excluding Overseas France.\n\n^ Testing data from 4 May to 12 May is missing because of the transition to the new reporting system SI-DEP.\n\n^ Excluding Abkhazia and South Ossetia.\n\n^ Data for residents only.\n\n^ Excluding Transnistria.\n\n^ Northern Cyprus is not recognized as a sovereign state by any country except Turkey.\n\n^ Includes data for Liechtenstein.\n\n^ Not a United Nations member.
  Date[a]
1 7 Sep 2020
2 30 Mar 2021
3 28 Aug 2022
4 10 Mar 2022
5 15 Oct 2022
6 .mw-parser-output .reflist{font-size:90%;margin-bottom:0.5em;list-style-type:decimal}.mw-parser-output .reflist .references{font-size:100%;margin-bottom:0;list-style-type:inherit}.mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}.mw-parser-output .reflist-columns{margin-top:0.3em}.mw-parser-output .reflist-columns ol{margin-top:0}.mw-parser-output .reflist-columns li{page-break-inside:avoid;break-inside:avoid-column}.mw-parser-output .reflist-upper-alpha{list-style-type:upper-alpha}.mw-parser-output .reflist-upper-roman{list-style-type:upper-roman}.mw-parser-output .reflist-lower-alpha{list-style-type:lower-alpha}.mw-parser-output .reflist-lower-greek{list-style-type:lower-greek}.mw-parser-output .reflist-lower-roman{list-style-type:lower-roman}\n^ Local time.\n\n^ For some countries it is unclear whether they report samples or cases. One person tested twice is recorded as one case and two samples.\n\n^ Excluding Taiwan.\n\n^ Excluding Northern Cyprus.\n\n^ Excluding Greenland and the Faroe Islands.\n\n^ Excluding Overseas France.\n\n^ Testing data from 4 May to 12 May is missing because of the transition to the new reporting system SI-DEP.\n\n^ Excluding Abkhazia and South Ossetia.\n\n^ Data for residents only.\n\n^ Excluding Transnistria.\n\n^ Northern Cyprus is not recognized as a sovereign state by any country except Turkey.\n\n^ Includes data for Liechtenstein.\n\n^ Not a United Nations member.
  Tested
1 2,630,000
2 3,179,074
3 45,772,571
4 3,301,860
5 2,529,087
6 .mw-parser-output .reflist{font-size:90%;margin-bottom:0.5em;list-style-type:decimal}.mw-parser-output .reflist .references{font-size:100%;margin-bottom:0;list-style-type:inherit}.mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}.mw-parser-output .reflist-columns{margin-top:0.3em}.mw-parser-output .reflist-columns ol{margin-top:0}.mw-parser-output .reflist-columns li{page-break-inside:avoid;break-inside:avoid-column}.mw-parser-output .reflist-upper-alpha{list-style-type:upper-alpha}.mw-parser-output .reflist-upper-roman{list-style-type:upper-roman}.mw-parser-output .reflist-lower-alpha{list-style-type:lower-alpha}.mw-parser-output .reflist-lower-greek{list-style-type:lower-greek}.mw-parser-output .reflist-lower-roman{list-style-type:lower-roman}\n^ Local time.\n\n^ For some countries it is unclear whether they report samples or cases. One person tested twice is recorded as one case and two samples.\n\n^ Excluding Taiwan.\n\n^ Excluding Northern Cyprus.\n\n^ Excluding Greenland and the Faroe Islands.\n\n^ Excluding Overseas France.\n\n^ Testing data from 4 May to 12 May is missing because of the transition to the new reporting system SI-DEP.\n\n^ Excluding Abkhazia and South Ossetia.\n\n^ Data for residents only.\n\n^ Excluding Transnistria.\n\n^ Northern Cyprus is not recognized as a sovereign state by any country except Turkey.\n\n^ Includes data for Liechtenstein.\n\n^ Not a United Nations member.
  Units[b]
1 samples
2 samples
3 samples
4 samples
5 samples
6 .mw-parser-output .reflist{font-size:90%;margin-bottom:0.5em;list-style-type:decimal}.mw-parser-output .reflist .references{font-size:100%;margin-bottom:0;list-style-type:inherit}.mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}.mw-parser-output .reflist-columns{margin-top:0.3em}.mw-parser-output .reflist-columns ol{margin-top:0}.mw-parser-output .reflist-columns li{page-break-inside:avoid;break-inside:avoid-column}.mw-parser-output .reflist-upper-alpha{list-style-type:upper-alpha}.mw-parser-output .reflist-upper-roman{list-style-type:upper-roman}.mw-parser-output .reflist-lower-alpha{list-style-type:lower-alpha}.mw-parser-output .reflist-lower-greek{list-style-type:lower-greek}.mw-parser-output .reflist-lower-roman{list-style-type:lower-roman}\n^ Local time.\n\n^ For some countries it is unclear whether they report samples or cases. One person tested twice is recorded as one case and two samples.\n\n^ Excluding Taiwan.\n\n^ Excluding Northern Cyprus.\n\n^ Excluding Greenland and the Faroe Islands.\n\n^ Excluding Overseas France.\n\n^ Testing data from 4 May to 12 May is missing because of the transition to the new reporting system SI-DEP.\n\n^ Excluding Abkhazia and South Ossetia.\n\n^ Data for residents only.\n\n^ Excluding Transnistria.\n\n^ Northern Cyprus is not recognized as a sovereign state by any country except Turkey.\n\n^ Includes data for Liechtenstein.\n\n^ Not a United Nations member.
  Confirmed(cases)
1 43,975
2 159,149
3 11,403,302
4 314,850
5 257,893
6 .mw-parser-output .reflist{font-size:90%;margin-bottom:0.5em;list-style-type:decimal}.mw-parser-output .reflist .references{font-size:100%;margin-bottom:0;list-style-type:inherit}.mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}.mw-parser-output .reflist-columns{margin-top:0.3em}.mw-parser-output .reflist-columns ol{margin-top:0}.mw-parser-output .reflist-columns li{page-break-inside:avoid;break-inside:avoid-column}.mw-parser-output .reflist-upper-alpha{list-style-type:upper-alpha}.mw-parser-output .reflist-upper-roman{list-style-type:upper-roman}.mw-parser-output .reflist-lower-alpha{list-style-type:lower-alpha}.mw-parser-output .reflist-lower-greek{list-style-type:lower-greek}.mw-parser-output .reflist-lower-roman{list-style-type:lower-roman}\n^ Local time.\n\n^ For some countries it is unclear whether they report samples or cases. One person tested twice is recorded as one case and two samples.\n\n^ Excluding Taiwan.\n\n^ Excluding Northern Cyprus.\n\n^ Excluding Greenland and the Faroe Islands.\n\n^ Excluding Overseas France.\n\n^ Testing data from 4 May to 12 May is missing because of the transition to the new reporting system SI-DEP.\n\n^ Excluding Abkhazia and South Ossetia.\n\n^ Data for residents only.\n\n^ Excluding Transnistria.\n\n^ Northern Cyprus is not recognized as a sovereign state by any country except Turkey.\n\n^ Includes data for Liechtenstein.\n\n^ Not a United Nations member.
  Confirmed /tested,%
1 1.7
2 5.0
3 24.9
4 9.5
5 10.2
6 .mw-parser-output .reflist{font-size:90%;margin-bottom:0.5em;list-style-type:decimal}.mw-parser-output .reflist .references{font-size:100%;margin-bottom:0;list-style-type:inherit}.mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}.mw-parser-output .reflist-columns{margin-top:0.3em}.mw-parser-output .reflist-columns ol{margin-top:0}.mw-parser-output .reflist-columns li{page-break-inside:avoid;break-inside:avoid-column}.mw-parser-output .reflist-upper-alpha{list-style-type:upper-alpha}.mw-parser-output .reflist-upper-roman{list-style-type:upper-roman}.mw-parser-output .reflist-lower-alpha{list-style-type:lower-alpha}.mw-parser-output .reflist-lower-greek{list-style-type:lower-greek}.mw-parser-output .reflist-lower-roman{list-style-type:lower-roman}\n^ Local time.\n\n^ For some countries it is unclear whether they report samples or cases. One person tested twice is recorded as one case and two samples.\n\n^ Excluding Taiwan.\n\n^ Excluding Northern Cyprus.\n\n^ Excluding Greenland and the Faroe Islands.\n\n^ Excluding Overseas France.\n\n^ Testing data from 4 May to 12 May is missing because of the transition to the new reporting system SI-DEP.\n\n^ Excluding Abkhazia and South Ossetia.\n\n^ Data for residents only.\n\n^ Excluding Transnistria.\n\n^ Northern Cyprus is not recognized as a sovereign state by any country except Turkey.\n\n^ Includes data for Liechtenstein.\n\n^ Not a United Nations member.
  Tested /population,%
1 7.7
2 11.0
3 46.4
4 19.0
5 17.0
6 .mw-parser-output .reflist{font-size:90%;margin-bottom:0.5em;list-style-type:decimal}.mw-parser-output .reflist .references{font-size:100%;margin-bottom:0;list-style-type:inherit}.mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}.mw-parser-output .reflist-columns{margin-top:0.3em}.mw-parser-output .reflist-columns ol{margin-top:0}.mw-parser-output .reflist-columns li{page-break-inside:avoid;break-inside:avoid-column}.mw-parser-output .reflist-upper-alpha{list-style-type:upper-alpha}.mw-parser-output .reflist-upper-roman{list-style-type:upper-roman}.mw-parser-output .reflist-lower-alpha{list-style-type:lower-alpha}.mw-parser-output .reflist-lower-greek{list-style-type:lower-greek}.mw-parser-output .reflist-lower-roman{list-style-type:lower-roman}\n^ Local time.\n\n^ For some countries it is unclear whether they report samples or cases. One person tested twice is recorded as one case and two samples.\n\n^ Excluding Taiwan.\n\n^ Excluding Northern Cyprus.\n\n^ Excluding Greenland and the Faroe Islands.\n\n^ Excluding Overseas France.\n\n^ Testing data from 4 May to 12 May is missing because of the transition to the new reporting system SI-DEP.\n\n^ Excluding Abkhazia and South Ossetia.\n\n^ Data for residents only.\n\n^ Excluding Transnistria.\n\n^ Northern Cyprus is not recognized as a sovereign state by any country except Turkey.\n\n^ Includes data for Liechtenstein.\n\n^ Not a United Nations member.
  Confirmed /population,%
1 0.13
2 0.55
3 11.6
4 1.8
5 1.7
6 .mw-parser-output .reflist{font-size:90%;margin-bottom:0.5em;list-style-type:decimal}.mw-parser-output .reflist .references{font-size:100%;margin-bottom:0;list-style-type:inherit}.mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}.mw-parser-output .reflist-columns{margin-top:0.3em}.mw-parser-output .reflist-columns ol{margin-top:0}.mw-parser-output .reflist-columns li{page-break-inside:avoid;break-inside:avoid-column}.mw-parser-output .reflist-upper-alpha{list-style-type:upper-alpha}.mw-parser-output .reflist-upper-roman{list-style-type:upper-roman}.mw-parser-output .reflist-lower-alpha{list-style-type:lower-alpha}.mw-parser-output .reflist-lower-greek{list-style-type:lower-greek}.mw-parser-output .reflist-lower-roman{list-style-type:lower-roman}\n^ Local time.\n\n^ For some countries it is unclear whether they report samples or cases. One person tested twice is recorded as one case and two samples.\n\n^ Excluding Taiwan.\n\n^ Excluding Northern Cyprus.\n\n^ Excluding Greenland and the Faroe Islands.\n\n^ Excluding Overseas France.\n\n^ Testing data from 4 May to 12 May is missing because of the transition to the new reporting system SI-DEP.\n\n^ Excluding Abkhazia and South Ossetia.\n\n^ Data for residents only.\n\n^ Excluding Transnistria.\n\n^ Northern Cyprus is not recognized as a sovereign state by any country except Turkey.\n\n^ Includes data for Liechtenstein.\n\n^ Not a United Nations member.
  Ref.
1 [189]
2 [190]
3 [191]
4 [192]
5 [3][193]
6 .mw-parser-output .reflist{font-size:90%;margin-bottom:0.5em;list-style-type:decimal}.mw-parser-output .reflist .references{font-size:100%;margin-bottom:0;list-style-type:inherit}.mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}.mw-parser-output .reflist-columns{margin-top:0.3em}.mw-parser-output .reflist-columns ol{margin-top:0}.mw-parser-output .reflist-columns li{page-break-inside:avoid;break-inside:avoid-column}.mw-parser-output .reflist-upper-alpha{list-style-type:upper-alpha}.mw-parser-output .reflist-upper-roman{list-style-type:upper-roman}.mw-parser-output .reflist-lower-alpha{list-style-type:lower-alpha}.mw-parser-output .reflist-lower-greek{list-style-type:lower-greek}.mw-parser-output .reflist-lower-roman{list-style-type:lower-roman}\n^ Local time.\n\n^ For some countries it is unclear whether they report samples or cases. One person tested twice is recorded as one case and two samples.\n\n^ Excluding Taiwan.\n\n^ Excluding Northern Cyprus.\n\n^ Excluding Greenland and the Faroe Islands.\n\n^ Excluding Overseas France.\n\n^ Testing data from 4 May to 12 May is missing because of the transition to the new reporting system SI-DEP.\n\n^ Excluding Abkhazia and South Ossetia.\n\n^ Data for residents only.\n\n^ Excluding Transnistria.\n\n^ Northern Cyprus is not recognized as a sovereign state by any country except Turkey.\n\n^ Includes data for Liechtenstein.\n\n^ Not a United Nations member.

## TASK 3: Pre-process and export the extracted data frame

The goal of task 3 is to pre-process the extracted data frame from the previous step, and export it as a csv file

Let's get a summary of the data frame

In [8]:
# Print the summary of the data frame
summary(covide19_data)

 Country or region    Date[a]             Tested            Units[b]
 Length:173         Length:173         Length:173         Length:173
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character
 Confirmed(cases)   Confirmed /tested,% Tested /population,%
 Length:173         Length:173          Length:173
 Class :character   Class :character    Class :character
 Mode  :character   Mode  :character    Mode  :character
 Confirmed /population,%     Ref.
 Length:173              Length:173
 Class :character        Class :character
 Mode  :character        Mode  :character

As you can see from the summary, the columns names are little bit different to understand and some column data types are not correct. For example, the `Tested` column shows as `character`.

As such, the data frame read from HTML table will need some pre-processing such as removing irrelvant columns, renaming columns, and convert columns into proper data types.

We have prepared a pre-processing function for you to conver the data frame but you can also try to write one by yourself

In [9]:
library(lubridate)

Attaching package: ‘lubridate’


The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union

In [10]:
preprocess_covid_data_frame <- function(data_frame) {

  #shape <- dim(data_frame)

  # Remove the World row
  #data_frame<-data_frame[!(data_frame$`Country.or.region`=="World"),]
  # Remove the last row
  data_frame <- data_frame[1:172, ]

  # We dont need the Units and Ref columns, so can be removed
  data_frame["Ref."] <- NULL
  data_frame["Units[b]"] <- NULL

  # Renaming the columns
  names(data_frame) <- c("country", "date", "tested", "confirmed", "confirmed.tested.ratio", "tested.population.ratio", "confirmed.population.ratio")

  # Convert column data types
  data_frame$country <- factor(data_frame$country)
  #data_frame$date <- as.factor(data_frame$date)
  data_frame$date <- dmy(data_frame$date)
  data_frame$tested <- as.numeric(gsub(",","",data_frame$tested))
  data_frame$confirmed <- as.numeric(gsub(",","",data_frame$confirmed))

  #data_frame$'confirmed.tested.ratio' <- gsub(",", "", data_frame$'confirmed.tested.ratio')
  data_frame$'confirmed.tested.ratio' <- as.numeric(data_frame$confirmed.tested.ratio)

  data_frame$'tested.population.ratio' <- gsub(",", "", data_frame$'tested.population.ratio')
  data_frame$'tested.population.ratio' <- as.numeric(data_frame$tested.population.ratio)

  data_frame$'confirmed.population.ratio' <- as.numeric(data_frame$confirmed.population.ratio)

  return(data_frame)
}

Call the `preprocess_covid_data_frame` function

In [11]:
# call `preprocess_covid_data_frame` function and assign it to a new data frame
covid19_preprocess <- preprocess_covid_data_frame(covide19_data)
head(covid19_preprocess)

  country             date       tested confirmed confirmed.tested.ratio
1 Afghanistan         2020-12-17 154767 49621     32.1
2 Albania             2021-02-18 428654 96838     22.6
3 Algeria             2020-11-02 230553 58574     25.4
4 Andorra             2022-02-23 300307 37958     12.6
5 Angola              2021-02-02 399228 20981      5.3
6 Antigua and Barbuda 2021-03-06  15268   832      5.4
  tested.population.ratio confirmed.population.ratio
1   0.40                   0.130
2  15.00                   3.400
3   0.53                   0.130
4 387.00                  49.000
5   1.30                   0.067
6  15.90                   0.860

Get the summary of the processed data frame again

In [12]:
# Print the summary of the processed data frame again
summary(covid19_preprocess)

                country         date                tested
 Afghanistan        :  1   Min.   :2020-07-31   Min.   :     3880
 Albania            :  1   1st Qu.:2021-05-30   1st Qu.:   512037
 Algeria            :  1   Median :2022-01-25   Median :  3029859
 Andorra            :  1   Mean   :2022-01-17   Mean   : 31377219
 Angola             :  1   3rd Qu.:2022-09-27   3rd Qu.: 12386725
 Antigua and Barbuda:  1   Max.   :2023-07-03   Max.   :929349291
 (Other)            :166
   confirmed        confirmed.tested.ratio tested.population.ratio
 Min.   :       0   Min.   : 0.00          Min.   :   0.006
 1st Qu.:   37839   1st Qu.: 5.00          1st Qu.:   9.475
 Median :  281196   Median :10.05          Median :  46.950
 Mean   : 2508340   Mean   :11.25          Mean   : 175.504
 3rd Qu.: 1278105   3rd Qu.:15.25          3rd Qu.: 156.500
 Max.   :90749469   Max.   :46.80          Max.   :3223.000

 confirmed.population.ratio
 Min.   : 0.000
 1st Qu.: 0.425
 Median : 6.100
 Mean   :12.769
 3rd Qu.:16.250
 Max.   :74.400

After pre-processing, you can see the columns and columns names are simplified, and columns types are converted into correct types.

The data frame has following columns:

- **country** - The name of the country
- **date** - Reported date
- **tested** - Total tested cases by the reported date
- **confirmed** - Total confirmed cases by the reported date
- **confirmed.tested.ratio** - The ratio of confirmed cases to the tested cases
- **tested.population.ratio** - The ratio of tested cases to the population of the country
- **confirmed.population.ratio** - The ratio of confirmed cases to the population of the country

OK, we can call `write.csv()` function to save the csv file into a file.

In [13]:
# Export the data frame to a csv file
write.csv(x = covid19_preprocess, row.names = FALSE, file = "covid.csv")

Note for IBM Waston Studio, there is no traditional "hard disk" associated with a R workspace.

Even if you call `write.csv()` method to save the data frame as a csv file, it won't be shown in IBM Cloud Object Storage asset UI automatically.

However, you may still check if the `covid.csv` exists using following code snippet:

In [14]:
# Get working directory
wd <- getwd()
# Get exported
file_path <- paste(wd, sep="", "/covid.csv")
# File path
print(file_path)
file.exists(file_path)

[1] "/content/covid.csv"

[1] TRUE

**Optional Step**: If you have difficulties finishing above webscraping tasks, you may still continue with next tasks by downloading a provided csv file from here:

In [15]:
## Download a sample csv file
# covid_csv_file <- download.file("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/dataset/covid.csv", destfile="covid.csv")
# covid_data_frame_csv <- read.csv("covid.csv", header=TRUE, sep=",")

## TASK 4: Get a subset of the extracted data frame

The goal of task 4 is to get the 5th to 10th rows from the data frame with only `country` and `confirmed` columns selected

In [16]:
# Read covid_data_frame_csv from the csv file
covid <- read.csv("covid.csv", stringsAsFactors = TRUE)

# Get the 5th to 10th rows, with two "country" "confirmed" columns
covid[5:10, c("country", "confirmed")]

   country             confirmed
5  Angola                 20981
6  Antigua and Barbuda      832
7  Argentina            9060495
8  Armenia               422963
9  Australia           10112229
10 Austria              5789991

## TASK 5: Calculate worldwide COVID testing positive ratio

The goal of task 5 is to get the total confirmed and tested cases worldwide, and try to figure the overall positive ratio using `confirmed cases / tested cases`

In [17]:
# Get the total confirmed cases worldwide
total_confirmed_cases <- sum(covid$confirmed)
total_confirmed_cases

# Get the total tested cases worldwide
total_tested_cases <- sum(covid$tested)
total_tested_cases

# Get the positive ratio (confirmed / tested)
positive_ratio <- total_confirmed_cases/total_tested_cases
positive_ratio

[1] 431434555

[1] 5396881644

[1] 0.07994145

## TASK 6: Get a country list which reported their testing data

The goal of task 6 is to get a catalog or sorted list of countries who have reported their COVID-19 testing data

In [18]:
library(dplyr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [22]:
# Get the `country` column
covid$country

# Check its class (should be Factor)
str(covid$country)

  [1] Afghanistan            Albania                Algeria
  [4] Andorra                Angola                 Antigua and Barbuda
  [7] Argentina              Armenia                Australia
 [10] Austria                Azerbaijan             Bahamas
 [13] Bahrain                Bangladesh             Barbados
 [16] Belarus                Belgium                Belize
 [19] Benin                  Bhutan                 Bolivia
 [22] Bosnia and Herzegovina Botswana               Brazil
 [25] Brunei                 Bulgaria               Burkina Faso
 [28] Burundi                Cambodia               Cameroon
 [31] Canada                 Chad                   Chile
 [34] China[c]               Colombia               Costa Rica
 [37] Croatia                Cuba                   Cyprus[d]
 [40] Czechia                Denmark[e]             Djibouti
 [43] Dominica               Dominican Republic     DR Congo
 [46] Ecuador                Egypt                  El Salvador
 [49] Equatorial Guinea      Estonia                Eswatini
 [52] Ethiopia               Faroe Islands          Fiji
 [55] Finland                France[f][g]           Gabon
 [58] Gambia                 Georgia[h]             Germany
 [61] Ghana                  Greece                 Greenland
 [64] Grenada                Guatemala              Guinea
 [67] Guinea-Bissau          Guyana                 Haiti
 [70] Honduras               Hungary                Iceland
 [73] India                  Indonesia              Iran
 [76] Iraq                   Ireland                Israel
 [79] Italy                  Ivory Coast            Jamaica
 [82] Japan                  Jordan                 Kazakhstan
 [85] Kenya                  Kosovo                 Kuwait
 [88] Kyrgyzstan             Laos                   Latvia
 [91] Lebanon                Lesotho                Liberia
 [94] Libya                  Lithuania              Luxembourg[i]
 [97] Madagascar             Malawi                 Malaysia
[100] Maldives               Mali                   Malta
[103] Mauritania             Mauritius              Mexico
[106] Moldova[j]             Mongolia               Montenegro
[109] Morocco                Mozambique             Myanmar
[112] Namibia                Nepal                  Netherlands
[115] New Caledonia          New Zealand            Niger
[118] Nigeria                North Korea            North Macedonia
[121] Northern Cyprus[k]     Norway                 Oman
[124] Pakistan               Palestine              Panama
[127] Papua New Guinea       Paraguay               Peru
[130] Philippines            Poland                 Portugal
[133] Qatar                  Romania                Russia
[136] Rwanda                 Saint Kitts and Nevis  Saint Lucia
[139] Saint Vincent          San Marino             Saudi Arabia
[142] Senegal                Serbia                 Singapore
[145] Slovakia               Slovenia               South Africa
[148] South Korea            South Sudan            Spain
[151] Sri Lanka              Sudan                  Sweden
[154] Switzerland[l]         Taiwan[m]              Tanzania
[157] Thailand               Togo                   Trinidad and Tobago
[160] Tunisia                Turkey                 Uganda
[163] Ukraine                United Arab Emirates   United Kingdom
[166] United States          Uruguay                Uzbekistan
[169] Venezuela              Vietnam                Zambia
[172] Zimbabwe
172 Levels: Afghanistan Albania Algeria Andorra Angola ... Zimbabwe

 Factor w/ 172 levels "Afghanistan",..: 1 2 3 4 5 6 7 8 9 10 ...

In [23]:
# Conver the country column into character so that you can easily sort them
covid$country <- as.character(covid$country)

In [24]:
  # Sort the countries AtoZ
AtoZ_countries <- covid %>%
  select(country) %>%
  arrange(country)

In [25]:
  # Sort the countries ZtoA
ZtoA_countries <- covid %>%
  select(country) %>%
  arrange(desc(country))

In [26]:
  # Print the sorted ZtoA list
print(list(ZtoA_countries))

[[1]]
                   country
1                 Zimbabwe
2                   Zambia
3                  Vietnam
4                Venezuela
5               Uzbekistan
6                  Uruguay
7            United States
8           United Kingdom
9     United Arab Emirates
10                 Ukraine
11                  Uganda
12                  Turkey
13                 Tunisia
14     Trinidad and Tobago
15                    Togo
16                Thailand
17                Tanzania
18               Taiwan[m]
19          Switzerland[l]
20                  Sweden
21                   Sudan
22               Sri Lanka
23                   Spain
24             South Sudan
25             South Korea
26            South Africa
27                Slovenia
28                Slovakia
29               Singapore
30                  Serbia
31                 Senegal
32            Saudi Arabia
33              San Marino
34           Saint Vincent
35             Saint Lucia
36   Saint Kitts and Nevis
37                  Rwanda
38                  Russia
39                 Romania
40                   Qatar
41                Portugal
42                  Poland
43             Philippines
44                    Peru
45                Paraguay
46        Papua New Guinea
47                  Panama
48               Palestine
49                Pakistan
50                    Oman
51                  Norway
52      Northern Cyprus[k]
53         North Macedonia
54             North Korea
55                 Nigeria
56                   Niger
57             New Zealand
58           New Caledonia
59             Netherlands
60                   Nepal
61                 Namibia
62                 Myanmar
63              Mozambique
64                 Morocco
65              Montenegro
66                Mongolia
67              Moldova[j]
68                  Mexico
69               Mauritius
70              Mauritania
71                   Malta
72                    Mali
73                Maldives
74                Malaysia
75                  Malawi
76              Madagascar
77           Luxembourg[i]
78               Lithuania
79                   Libya
80                 Liberia
81                 Lesotho
82                 Lebanon
83                  Latvia
84                    Laos
85              Kyrgyzstan
86                  Kuwait
87                  Kosovo
88                   Kenya
89              Kazakhstan
90                  Jordan
91                   Japan
92                 Jamaica
93             Ivory Coast
94                   Italy
95                  Israel
96                 Ireland
97                    Iraq
98                    Iran
99               Indonesia
100                  India
101                Iceland
102                Hungary
103               Honduras
104                  Haiti
105                 Guyana
106          Guinea-Bissau
107                 Guinea
108              Guatemala
109                Grenada
110              Greenland
111                 Greece
112                  Ghana
113                Germany
114             Georgia[h]
115                 Gambia
116                  Gabon
117           France[f][g]
118                Finland
119                   Fiji
120          Faroe Islands
121               Ethiopia
122               Eswatini
123                Estonia
124      Equatorial Guinea
125            El Salvador
126                  Egypt
127                Ecuador
128     Dominican Republic
129               Dominica
130               Djibouti
131             Denmark[e]
132               DR Congo
133                Czechia
134              Cyprus[d]
135                   Cuba
136                Croatia
137             Costa Rica
138               Colombia
139               China[c]
140                  Chile
141                   Chad
142                 Canada
143               Cameroon
144               Cambodia
145                Burundi
146           Burkina Faso
147               Bulgaria
148                 Brunei
149                 Brazil
150               Botswana
151 Bosnia and Herzegovina
152                Bolivia
153                 Bhutan
154                  Benin
155                 Belize
156                Belgium
157                Belarus
158               Barbados
159             Bangladesh
160                Bahrain
161                Bahamas
162             Azerbaijan
163                Austria
164              Australia
165                Armenia
166              Argentina
167    Antigua and Barbuda
168                 Angola
169                Andorra
170                Algeria
171                Albania
172            Afghanistan

## TASK 7: Identify countries names with a specific pattern

The goal of task 7 is using a regular expression to find any countires start with `United`

In [27]:
# Use a regular expression `United.+` to find matches
pattern <- "^United"
matching_countries <- covid$country[grep(pattern, covid$country)]

# Print the matched country names
matching_countries

[1] "United Arab Emirates" "United Kingdom"       "United States"

## TASK 8: Pick two countries you are interested, and then review their testing data

The goal of task 8 is to compare the COVID-19 test data between two countires, you will need to select two rows from the dataframe, and select `country`, `confirmed`, `confirmed-population-ratio` columns

In [28]:
# Select a subset (should be only one row) of data frame based on a selected country name and columns
selected_columns <- c("country", "confirmed", "confirmed.population.ratio")
benin_subset <- subset(covid, country == "Benin", select = selected_columns)
benin_subset

# Select a subset (should be only one row) of data frame based on a selected country name and columns
germany_subset <- subset(covid, country == "Germany", select = selected_columns)
germany_subset

   country confirmed confirmed.population.ratio
19 Benin   7884      0.067

   country confirmed confirmed.population.ratio
60 Germany 3733519   4.5

## TASK 9: Compare which one of the selected countries has a larger ratio of confirmed cases to population

The goal of task 9 is to find out which country you have selected before has larger ratio of confirmed cases to population, which may indicate that country has higher COVID-19 infection risk

In [29]:
if (benin_subset$confirmed.population.ratio > germany_subset$confirmed.population.ratio) {
  print(benin_subset$country)
} else {
  print(germany_subset$country)
}

[1] "Germany"

## TASK 10: Find countries with confirmed to population ratio rate less than a threshold

The goal of task 10 is to find out which countries have the confirmed to population ratio less than 1%, it may indicate the risk of those countries are relatively low

In [30]:
# Get a subset of any countries with `confirmed.population.ratio` less than the threshold
covid %>%
  filter(confirmed.population.ratio < 0.01) %>%
  pull(country)

[1] "Burundi"     "China[c]"    "Laos"        "North Korea" "Tanzania"